[tox]
isolated_build = True
envlist = py312, lint
skipsdist = True

[testenv]
allowlist_externals = poetry
commands =
    poetry run pytest -q tests/

[testenv:lint]
commands =
    poetry run black --check -l 100 src/ tests/
    poetry run python -m compileall -q src/