defaults:
  - _self_
  - dataset: rabbit
  - model: koopman_ae
  - trainer: default
  - optim: optuna

dataset:
  batch_size: 64
  num_workers: 4

save_dirs:
  figures: ./figures
  
wandb:
  project: koopman-control
  mode: disabled