defaults:
  - _self_
  - model: koopman_ae
  - trainer: default
  - optim: optuna

name: fusion-no-count-loss

dataset:
  batch_size: 64
  dataset_name: rabbit
  data_dir: ./data/rabbit_grass_sweeps_oscil
  csv_file:

save_dirs:
  figures: ./figures
  
wandb:
  project: koopman-control
  mode: disabled